{{- if .Values.tls }}
{{- if .Values.tls.certificates }}
{{- range $certName, $certData := .Values.tls.certificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $certName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "openshift-ingress.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $certData.cert | b64enc }}
  tls.key: {{ $certData.key | b64enc }}
{{- end }}
{{- end }}
{{- end }}
